name = "sukka"
description = "SukkaLab sing-box rules merged by filename"

[source.archive]
src = "https://api.github.com/repos/SukkaLab/ruleset.skk.moe/tarball"
sha256 = "SKIP"

[build]
type = "sukka"

[beyond]
command = [
    'mv -v "$PKGDIR/china-ip.json" "$PKGDIR/cn.json"',
    'mv -v "$PKGDIR/china-ip.srs" "$PKGDIR/cn.srs"'
]

[publish]
target = "domain"

[publish.files]
"cn.json" = "ip"
"cn.srs" = "ip"
