[__config__]
input = "dlc.dat"
version = 2

[category-ads-all]
input = "geosite.dat"
bases = ["category-ads-all"]

[geolocation-cn]
bases = ["geolocation-cn"]
attr_filters = ["lacks:!cn", "lacks:ads"]

["base-!cn"]
bases = ["geolocation-!cn"]
attr_filters = ["lacks:cn", "lacks:ads"]
internal = true

["geolocation-!cn"]
depends = ["base-!cn"]
bases = ["google", "microsoft"]

[private]
bases = ["private"]

[connectivity-check]
bases = ["connectivity-check"]

