[__config__]
input = "dlc.dat"
version = 2

[geosite-category-ads-all]
input = "geosite.dat"
bases = ["category-ads-all"]

[geosite-geolocation-cn]
bases = ["geolocation-cn"]
attr_filters = ["lacks:!cn", "lacks:ads"]

["base-!cn"]
bases = ["geolocation-!cn"]
attr_filters = ["lacks:cn", "lacks:ads"]
internal = true

["geosite-geolocation-!cn"]
depends = ["base-!cn"]
bases = ["google", "microsoft"]

[geosite-private]
bases = ["private"]

[geosite-connectivity-check]
bases = ["connectivity-check"]

